name: Compile LaTeX

on:
  push:
    branches: [ "diploma" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup TeX Live
      uses: teXtworld/setup-texlive@v1
      with:
        packages: >
          scheme-full
          latexmk

    - name: Compile LaTeX document
      run: |
        latexmk -lualatex -interaction=nonstopmode vkr.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: vkr-pdf
        path: vkr.pdf
